modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="divinityladder"
version="${file.jarVersion}"
displayName="Divinity Latter"
logoFile="divinityladder.png"
credits="uuz phoximity"
authors="uuz phoximity"
description='''
In a world beyond our own,
Where gods and mortals roam,
Survival is the only goal,
As we battle for our home.
The gods, they reign supreme,
But we refuse to bow,
We'll fight until our dying breath,
To take them down somehow.
The stories of this world are told,
Of heroes brave and bold,
Who dared to challenge divine might,
And fought with all their might.
The ancient tales still resonate,
Of battles fought with hate,
Of mortals who defied the gods,
And sealed their own fate.
So we take up our swords and shields,
And march into the fray,
For in this world of gods and beasts,
Only the strong will stay.



In a world beyond our own,
Where gods and monsters roam,
Survival is a constant quest,
And killing deities, a dangerous test.
A story unfolds with each passing day,
Of heroes and villains in a deadly fray,
With magic and sword, they battle on,
Until the fateful day, when one is gone.
The gods are not kind, nor merciful too,
Their whims and desires, they impose on you,
But brave souls rise up, to challenge their might,
And fight for freedom, in the dark of night.
In this world of wonder and dread,
Where the living and dead are wed,
We journey on, with hope and fear,
For the end draws near, and the story is clear.

'''
[[dependencies.divinityladder]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.divinityladder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
